FROM mcr.microsoft.com/dotnet/sdk:9.0 AS dev
WORKDIR /src

COPY ["RAGNet.Domain/RAGNet.Domain.csproj", "RAGNet.Domain/"]
COPY ["RAGNet.Infrastructure/RAGNet.Infrastructure.csproj", "RAGNet.Infrastructure/"]
COPY ["RAGNet.Application/RAGNet.Application.csproj", "RAGNet.Application/"]
COPY ["web/web.csproj", "web/"]

RUN dotnet restore "web/web.csproj"

COPY . .

WORKDIR "/src/web"

CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]