version: "3.8"

services:
  api-dev:
    container_name: api-dev
    build:
      context: ./api
      dockerfile: /web/Dockerfile.dev
    volumes:
      - ./api:/src:delegated
      - /src/bin
      - /src/obj
    ports:
      - "5000:8080"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    command:
      [
        "dotnet",
        "watch",
        "run",
        "--project",
        "web.csproj",
        "--urls",
        "http://0.0.0.0:8080",
      ]
    depends_on:
      - postgres
      - qdrant

  client-dev:
    container_name: client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["pnpm", "run", "start", "--poll", "200"]

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data:
