services:
  api-dev:
    build:
      context: ./api
      dockerfile: web/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - qdrant
    environment:
      - CLIENT_URL=http://localhost:4200
      - PRODUCTION=false
  client-dev:
    container_name: client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["pnpm", "run", "start", "--poll", "200"]

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  migrations:
    build:
      context: ./api
      dockerfile: RAGNet.Infrastructure/Persistence/Dockerfile
      target: migrations
    depends_on:
      - postgres
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rag_user
      RABBITMQ_DEFAULT_PASS: rag_password
      RABBITMQ_SSL_CACERTFILE: /certs/ca_certificate.pem
      RABBITMQ_SSL_CERTFILE: /certs/server_certificate.pem
      RABBITMQ_SSL_KEYFILE: /certs/server_key.pem
    volumes:
      - ./certs:/certs:ro

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

volumes:
  rabbitmq_data:
  postgres_data:
  qdrant_data:
