// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RAGNET.Infrastructure.Database;

#nullable disable

namespace RAGNet.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250630152746_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.Chunkers.Chunker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("Chunkers", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.Documents.Pages.Chunks.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("PageId");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("VectorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("VectorId");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("Chunks", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.Documents.Pages.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("DocumentId");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("Text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Pages", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.ProvidersApiKeys.ProviderApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ProviderApiKeys", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.QueryEnhancers.QueryEnhancer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxQueries")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("QueryEnhancers", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.QueryResultFilters.QueryResultFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int>("Strategy")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("Filters", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.Rankers.Ranker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Rankers", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.TokenWallets.TokenTransactions.TokenTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CostValue")
                        .HasColumnType("bigint")
                        .HasColumnName("Cost");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TokenWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("TokenWalletId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenWalletId");

                    b.ToTable("TokenTransactions", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.TokenWallets.TokenWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("FreeTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("FreeTokens");

                    b.Property<DateTime>("LastFreeTokenResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PaidTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("PaidTokens");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TokenWallets", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.Users.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExpiresAt");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PaymentId");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("Plan");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SubscribedAt");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SubscriptionId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.Workflows.CallbackUrls.CallbackUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("CallbackUrls", (string)null);
                });

            modelBuilder.Entity("RAGNET.Domain.Workflows.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastEmbeddedDocumentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastQueryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TokenUsage")
                        .HasColumnType("bigint")
                        .HasColumnName("TokenUsage");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RAGNET.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RAGNET.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RAGNET.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RAGNET.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RAGNET.Domain.Chunkers.Chunker", b =>
                {
                    b.HasOne("RAGNET.Domain.Workflows.Workflow", "Workflow")
                        .WithOne("Chunker")
                        .HasForeignKey("RAGNET.Domain.Chunkers.Chunker", "WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("RAGNET.Domain.SharedKernel.Metas.Meta", "Metas", b1 =>
                        {
                            b1.Property<Guid>("ChunkerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Key")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("ChunkerId", "Key");

                            b1.ToTable("ChunkerMetas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ChunkerId");
                        });

                    b.Navigation("Metas");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("RAGNET.Domain.Documents.Document", b =>
                {
                    b.HasOne("RAGNET.Domain.Workflows.Workflow", "Workflow")
                        .WithMany("Documents")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("RAGNET.Domain.Documents.Pages.Chunks.Chunk", b =>
                {
                    b.HasOne("RAGNET.Domain.Documents.Pages.Page", "Page")
                        .WithMany("Chunks")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("RAGNET.Domain.Documents.Pages.Page", b =>
                {
                    b.HasOne("RAGNET.Domain.Documents.Document", "Document")
                        .WithMany("Pages")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RAGNET.Domain.ProvidersApiKeys.ProviderApiKey", b =>
                {
                    b.HasOne("RAGNET.Domain.Users.User", null)
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RAGNET.Domain.SharedKernel.Providers.Provider", "Provider", b1 =>
                        {
                            b1.Property<Guid>("ProviderApiKeyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ProviderType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Provider");

                            b1.HasKey("ProviderApiKeyId");

                            b1.ToTable("ProviderApiKeys");

                            b1.WithOwner()
                                .HasForeignKey("ProviderApiKeyId");

                            b1.OwnsOne("RAGNET.Domain.Users.ApiKeys.ApiKey", "ApiKey", b2 =>
                                {
                                    b2.Property<Guid>("ProviderApiKeyId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("ApiKey");

                                    b2.HasKey("ProviderApiKeyId");

                                    b2.ToTable("ProviderApiKeys");

                                    b2.WithOwner()
                                        .HasForeignKey("ProviderApiKeyId");
                                });

                            b1.Navigation("ApiKey")
                                .IsRequired();
                        });

                    b.Navigation("Provider")
                        .IsRequired();
                });

            modelBuilder.Entity("RAGNET.Domain.QueryEnhancers.QueryEnhancer", b =>
                {
                    b.HasOne("RAGNET.Domain.Workflows.Workflow", "Workflow")
                        .WithMany("QueryEnhancers")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("RAGNET.Domain.SharedKernel.Metas.Meta", "Metas", b1 =>
                        {
                            b1.Property<Guid>("QueryEnhancerId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("QueryEnhancerId", "Id");

                            b1.ToTable("QueryEnhancerMetas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("QueryEnhancerId");
                        });

                    b.Navigation("Metas");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("RAGNET.Domain.QueryResultFilters.QueryResultFilter", b =>
                {
                    b.HasOne("RAGNET.Domain.Workflows.Workflow", "Workflow")
                        .WithOne("QueryResultFilter")
                        .HasForeignKey("RAGNET.Domain.QueryResultFilters.QueryResultFilter", "WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("RAGNET.Domain.SharedKernel.Metas.Meta", "Metas", b1 =>
                        {
                            b1.Property<Guid>("FilterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("FilterId", "Id");

                            b1.ToTable("FilterMetas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FilterId");
                        });

                    b.Navigation("Metas");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("RAGNET.Domain.Rankers.Ranker", b =>
                {
                    b.HasOne("RAGNET.Domain.Workflows.Workflow", "Workflow")
                        .WithMany("Rankers")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("RAGNET.Domain.SharedKernel.Metas.Meta", "Metas", b1 =>
                        {
                            b1.Property<Guid>("RankerId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("RankerId", "Id");

                            b1.ToTable("RankerMetas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RankerId");
                        });

                    b.Navigation("Metas");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("RAGNET.Domain.TokenWallets.TokenTransactions.TokenTransaction", b =>
                {
                    b.HasOne("RAGNET.Domain.TokenWallets.TokenWallet", "TokenWallet")
                        .WithMany("Transactions")
                        .HasForeignKey("TokenWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TokenWallet");
                });

            modelBuilder.Entity("RAGNET.Domain.TokenWallets.TokenWallet", b =>
                {
                    b.HasOne("RAGNET.Domain.Users.User", null)
                        .WithOne("TokenWallet")
                        .HasForeignKey("RAGNET.Domain.TokenWallets.TokenWallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RAGNET.Domain.Users.Subscriptions.Subscription", b =>
                {
                    b.HasOne("RAGNET.Domain.Users.User", null)
                        .WithOne("Subscription")
                        .HasForeignKey("RAGNET.Domain.Users.Subscriptions.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RAGNET.Domain.SharedKernel.Subscriptions.SubscriptionPlan", "ScheduledPlan", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ScheduledPlan");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.Navigation("ScheduledPlan");
                });

            modelBuilder.Entity("RAGNET.Domain.Workflows.CallbackUrls.CallbackUrl", b =>
                {
                    b.HasOne("RAGNET.Domain.Workflows.Workflow", null)
                        .WithMany("CallbackUrls")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RAGNET.Domain.Workflows.Workflow", b =>
                {
                    b.HasOne("RAGNET.Domain.Users.User", null)
                        .WithMany("Workflows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RAGNET.Domain.SharedKernel.Providers.ConversationProviderConfig", "ConversationProviderConfig", b1 =>
                        {
                            b1.Property<Guid>("WorkflowId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ConversationModel");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("ConversationProvider");

                            b1.HasKey("WorkflowId");

                            b1.ToTable("Workflows");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowId");
                        });

                    b.OwnsOne("RAGNET.Domain.SharedKernel.Providers.EmbeddingProviderConfig", "EmbeddingProviderConfig", b1 =>
                        {
                            b1.Property<Guid>("WorkflowId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("EmbeddingModel");

                            b1.Property<int>("Provider")
                                .HasColumnType("integer")
                                .HasColumnName("EmbeddingProvider");

                            b1.Property<int>("VectorSize")
                                .HasColumnType("integer")
                                .HasColumnName("VectorSize");

                            b1.HasKey("WorkflowId");

                            b1.ToTable("Workflows");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowId");
                        });

                    b.Navigation("ConversationProviderConfig")
                        .IsRequired();

                    b.Navigation("EmbeddingProviderConfig")
                        .IsRequired();
                });

            modelBuilder.Entity("RAGNET.Domain.Documents.Document", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("RAGNET.Domain.Documents.Pages.Page", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("RAGNET.Domain.TokenWallets.TokenWallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RAGNET.Domain.Users.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Subscription")
                        .IsRequired();

                    b.Navigation("TokenWallet")
                        .IsRequired();

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("RAGNET.Domain.Workflows.Workflow", b =>
                {
                    b.Navigation("CallbackUrls");

                    b.Navigation("Chunker")
                        .IsRequired();

                    b.Navigation("Documents");

                    b.Navigation("QueryEnhancers");

                    b.Navigation("QueryResultFilter");

                    b.Navigation("Rankers");
                });
#pragma warning restore 612, 618
        }
    }
}
